# Generated by Django 3.1.3 on 2020-12-25 08:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Romanticism', 'Romanticism'), ('Drama', 'Drama'), ('Tradegy', 'Tradegy')], default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[(django.contrib.auth.models.User, django.contrib.auth.models.User)], default=0, max_length=20)),
            ],
        ),
    ]
