# Generated by Django 3.1.3 on 2020-12-25 08:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUTHORS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[(django.contrib.auth.models.User, django.contrib.auth.models.User)], default=0, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='USER',
        ),
    ]
