# Generated by Django 3.1.3 on 2020-12-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0002_auto_20201225_0054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AUTHORS',
            new_name='AUTHOR',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
