# Generated by Django 3.1.3 on 2020-12-25 09:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0004_auto_20201225_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.CharField(choices=[(django.contrib.auth.models.User, django.contrib.auth.models.User)], default=0, max_length=20),
        ),
    ]
