# Generated by Django 3.1.3 on 2020-12-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0007_auto_20201225_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='blog/banners'),
        ),
    ]
