# Generated by Django 3.1.3 on 2020-12-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0008_auto_20201225_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_pic',
            field=models.ImageField(default='blog/banner/avatar.jpg', upload_to='blog/profile_pic'),
        ),
    ]
