# Generated by Django 3.1.3 on 2020-12-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0009_blog_author_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_pic',
            field=models.ImageField(default='avatar.jpg', upload_to='blog/profile_pic'),
        ),
    ]
