# Generated by Django 3.1.3 on 2020-12-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0010_auto_20201225_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
