# Generated by Django 3.1.3 on 2020-12-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0012_blog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
