# Generated by Django 3.1.3 on 2020-12-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0013_auto_20201225_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.TimeField(auto_created=True, auto_now_add=True),
        ),
    ]
