# Generated by Django 3.1.3 on 2020-12-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0014_auto_20201225_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='time',
        ),
    ]
