# Generated by Django 3.1.3 on 2020-12-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0016_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
