# Generated by Django 3.1.3 on 2020-12-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyyard', '0020_blog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_pic',
            field=models.ImageField(default='banners/avatar.jpg', upload_to='blog/profile_pic'),
        ),
    ]
